const products = [
  {
    id: 0,
    image: '../assets/products/lima_beans.png',
    name: 'Lima Beans - 1B',
    price: 18500,
    numberOfUnits: 1,
  },
  {
    id: 1,
    image: '../assets/products/white_beans.png',
    name: 'White Beans - 1B',
    price: 10000,
    numberOfUnits: 1,
  },
  {
    id: 2,
    image: '../assets/products/corn.png',
    name: 'Corn - 15kg',
    price: 18500,
    numberOfUnits: 1,
  },
  {
    id: 3,
    image: '../assets/products/rice.png',
    name: '50 kg bag of Rice',
    price: 24500,
    numberOfUnits: 1,
  },
  {
    id: 4,
    image: '../assets/products/millet.png',
    name: '50 kg bag of Millet',
    price: 18500,
    numberOfUnits: 1,
  },
  {
    id: 5,
    image: '../assets/products/ginger.png',
    name: 'Ginger - 1KG',
    price: 12000,
    numberOfUnits: 1,
  },
  {
    id: 6,
    image: '../assets/products/fresh_peas.png',
    name: 'Fresh Peas - 1B',
    price: 12500,
    numberOfUnits: 1,
  },
  {
    id: 7,
    image: '../assets/products/yam.png',
    name: '5 Tubers of Yam',
    price: 15000,
    numberOfUnits: 1,
  },
  {
    id: 8,
    image: '../assets/products/soya_beans.png',
    name: 'Soya Beans - 1B',
    price: 10000,
    numberOfUnits: 1,
  },
  {
    id: 9,
    image: '../assets/products/quinoa.png',
    name: '500g Pack of Quinoa',
    price: 15500,
    numberOfUnits: 1,
  },
  {
    id: 10,
    image: '../assets/products/cassava.png',
    name: '5 Tubers of Cassava',
    price: 17500,
    numberOfUnits: 1,
  },
  {
    id: 11,
    image: '../assets/products/carrot.png',
    name: 'Carrot - 1Kg',
    price: 10500,
    numberOfUnits: 1,
  },
];